{{- if .Values.debezium.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conversational-ai-scylladb.fullname" . }}-debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "conversational-ai-scylladb.fullname" . }}-debezium
  template:
    metadata:
      labels:
        app: {{ include "conversational-ai-scylladb.fullname" . }}-debezium
    spec:
      containers:
      - name: debezium
        image: "{{ .Values.debezium.image.repository }}:{{ .Values.debezium.image.tag }}"
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: "{{ include "conversational-ai-scylladb.fullname" . }}-kafka:9092"
        - name: GROUP_ID
          value: {{ .Values.debezium.config.groupId }}
        - name: CONFIG_STORAGE_TOPIC
          value: {{ .Values.debezium.config.configStorageTopic }}
        - name: OFFSET_STORAGE_TOPIC
          value: {{ .Values.debezium.config.offsetStorageTopic }}
        - name: STATUS_STORAGE_TOPIC
          value: {{ .Values.debezium.config.statusStorageTopic }}
        - name: CONNECT_SCHEMA_REGISTRY_URL
          value: "http://{{ include "conversational-ai-scylladb.fullname" . }}-schema-registry:8081"
{{- end }}
