{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "conversational-ai-scylladb.fullname" . }}-kafka
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "conversational-ai-scylladb.fullname" . }}-kafka
  template:
    metadata:
      labels:
        app: {{ include "conversational-ai-scylladb.fullname" . }}-kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ include "conversational-ai-scylladb.fullname" . }}-zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://{{ include "conversational-ai-scylladb.fullname" . }}-kafka:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
      volumes:
      - name: kafka-data
        {{- if .Values.kafka.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "conversational-ai-scylladb.fullname" . }}-kafka-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}

