apiVersion: v1
kind: Service
metadata:
  name: {{ include "conversational-ai-scylladb.fullname" . }}
  labels:
    {{- include "conversational-ai-scylladb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - port: {{ .Values.service.port }}
    targetPort: cql
    protocol: TCP
    name: cql
  - port: {{ .Values.service.prometheusPort }}
    targetPort: prometheus
    protocol: TCP
    name: prometheus
  selector:
    {{- include "conversational-ai-scylladb.selectorLabels" . | nindent 4 }}
